### ISSUE TITLE
Yahtzee To-Do

### ISSUE THREAD

**Issue by linsydeanna** [linsydeanna/yahtzee#1]
- [ ] User can click the score button even if no score was selected
- [x] Score areas need styling fixes
- [x] User can score even if roll was not completed
- [x] Need dice animation to assist user with turns
- [ ] User can change scores
- [ ] User can keep playing after 13 turns
- [x] Bonus doesn't work
- [ ] Score sections aren't totaling
- [ ] Total score isn't displaying
- [x] Roll and score buttons should be different colors
- [ ] Table styling
- [ ] Score remains in score area after dice are re-rolled
- [x] Remove extra border from dice
- [ ] User can score even if they did not achieve the category
